<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Version>1.0.1.0</Version>
        <RootNamespace>Jellyfin.Plugin.Catalogue</RootNamespace>
        <AssemblyName>Jellyfin.Plugin.Catalogue</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Jellyfin.Common" Version="12.1.0" />
        <PackageReference Include="Jellyfin.Model" Version="12.1.0" />
        <PackageReference Include="Jellyfin.Controller" Version="12.1.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Configuration\configPage.html" />
        <None Remove="Inject\catalogue-link.js" />
        <EmbeddedResource Include="Inject\catalogue-link.js" />
    </ItemGroup>

</Project>
